# https://travis-ci.org/DD-L/socks-proxy-tester
language: python
    - 2.7.8
    #- 2.7

install:
    #- if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then travis_retry pip install PySocks requests requesocks; fi
    #- pip install PySocks requests requesocks
    #- pip install --upgrade pip
    - sudo pip install PySocks
    - sudo pip install SocksiPy-branch
    #- sudo apt-get install python-socksipy
    - sudo pip install requests
    - sudo pip install requesocks

script:
    - sudo python socks-proxy-test.py auto 1000

sudo: required
