# https://travis-ci.org/DD-L/socks-proxy-tester
language: python
    - 2.7.8
    - 2.7

install:
    #- if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then travis_retry sudo pip install PySocks requests requesocks; fi
    - sudo pip install PySocks
    - sudo pip install requests
    - sudo pip install requesocks

script:
    - sudo python socks-proxy-test.py auto 1000

sudo: required
